### ISSUE TITLE
Questions on Data donwload

### ISSUE THREAD

**Issue by Buzz-Beater** [iejMac/clip-video-encode#58]
Hi, Thanks for the good work. I was trying to make use of the pre-extracted video features on WebVid10M and was wondering if there could be any instructions on that. I followed the huggingface dataset hub instructions and wasn't able to download it correctly as it is recording some ''missing metadata'' error.

**Comment by iejMac** [comment]
@Buzz-Beater Hmmm yeah I should probably make some example for how to use the our WebDataset format. So we just store the data on huggingface but in order to use it you need to use your dataset reader class. What you want to do is download the tar files from huggingface by cloning the dataset, then you want to run to 'git lfs install' inside the cloned dataset repository. At that point you'll have the tar files downloaded and you want to input them into [this](https://github.com/iejMac/clip-video-encode/blob/main/clip_video_encode/dataset/dataset_reader.py) class, you can just import it via ```from clip_video_encode.dataset import EmbeddingWebDatasetReader```. After that you can initialize with a string like: '/path/to/tar/files/{000000000..000001082}.tar' for the val_urls parameter. Double check how many tars there are, I think I remember 1082 but there may be more/less.

**Comment by Buzz-Beater** [comment]
Got it, thanks for the instructions!
